version: '3.8'

services:
  backend:
    build: .
    container_name: trip_manager
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongoDB
    networks:
      - app-network

  mongoDB:
    image: mongo:latest
    container_name: mongo_db
    env_file:
      - .env
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
